services:
  db:
    image: postgres:17 
    container_name: db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - pg-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_PORT: ${DATABASE_PORT}
    env_file: .env
    attach: false

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pg-network
    attach: false

  gateway:
    build:
      context: .
      dockerfile: src/backend_services/gateway/Dockerfile
    container_name: gateway
    ports:
      - ${API_SERVICE_PORT}:${API_SERVICE_PORT}
    networks:
      - pg-network
    volumes:
      - ./src/backend_services/gateway:/api/gateway
    command: uvicorn gateway:app --host 0.0.0.0 --port 8000

  account:
    build:
      context: .
      dockerfile: src/backend_services/account/Dockerfile
    container_name: account
    ports:
      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}
    networks:
      - pg-network
    volumes:
      - ./src/backend_services/account:/api/account
    command: python -m account.server


networks:
  pg-network:


volumes:
  pgadmin-data:
  postgres_data:
