# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from account.proto import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in auth_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AccountAuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AccountRegistration = channel.unary_unary(
            "/account_auth.AccountAuthService/AccountRegistration",
            request_serializer=auth__pb2.AccountRegistrationRequest.SerializeToString,
            response_deserializer=auth__pb2.AccountResponse.FromString,
            _registered_method=True,
        )
        self.AccountLogin = channel.unary_unary(
            "/account_auth.AccountAuthService/AccountLogin",
            request_serializer=auth__pb2.AccountLoginRequest.SerializeToString,
            response_deserializer=auth__pb2.AccountResponse.FromString,
            _registered_method=True,
        )


class AccountAuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AccountRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AccountLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AccountAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AccountRegistration": grpc.unary_unary_rpc_method_handler(
            servicer.AccountRegistration,
            request_deserializer=auth__pb2.AccountRegistrationRequest.FromString,
            response_serializer=auth__pb2.AccountResponse.SerializeToString,
        ),
        "AccountLogin": grpc.unary_unary_rpc_method_handler(
            servicer.AccountLogin,
            request_deserializer=auth__pb2.AccountLoginRequest.FromString,
            response_serializer=auth__pb2.AccountResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "account_auth.AccountAuthService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "account_auth.AccountAuthService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AccountAuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AccountRegistration(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/account_auth.AccountAuthService/AccountRegistration",
            auth__pb2.AccountRegistrationRequest.SerializeToString,
            auth__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AccountLogin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/account_auth.AccountAuthService/AccountLogin",
            auth__pb2.AccountLoginRequest.SerializeToString,
            auth__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
