name: Backend API CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Black
        run: pip install black

      - name: Run Black (check only)
        run: black --check .

  linting-check:
    needs: black-format-check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Sync Packages
        run: |
          pip install uv
          uv sync

      # Main linter check used to format codebase
      - name: Run mypy
        run: |
          uv run mypy .

      # Extra linter check targeting specific issues not covered by base linter
      - name: Run flake8
        run: |
          uv run flake8 src/

  tests:
    needs: linting-check
    runs-on: ubuntu-latest

    services:
      postgres-testing:
        image: postgres:16
        env:
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
        ports:
          - 5435:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Sync Packages
        run: |
          pip install uv
          uv sync

      - name: Run Unit Tests
        run: uv run pytest -v src/backend_services/tests/unit --cov=src
        env:
          PYTHON_ENV: testing

          TEST_DATABASE_USERNAME: testing
          TEST_DATABASE_PASSWORD: testing
          TEST_DATABASE_HOST: localhost
          TEST_DATABASE_PORT: 5435

          ACCOUNT_SERVICE_HOST: localhost
          ACCOUNT_SERVICE_PORT: 50000
          ACCOUNT_SERVICE_MAX_WORKERS: 10
